version: '3'
services:
  prometheus:
    image:
      prom/prometheus
    container_name:
      prometheus
    hostname:
      prometheus
    restart:
      unless-stopped
    volumes:
      - $PROMETHEUS_VOLUME:/prometheus
    ports:
      - '9090:9090'

networks:
  network1:
      name: my-pre-existing-network
      external: true
