version: '3'
services:
  prometheus:
    image:
      prom/prometheus
    container_name:
      prometheus
    hostname:
      prometheus
    restart:
      unless-stopped
    volumes:
      - $PROMETHEUS_VOLUME:/prometheus
    ports:
      - '9090:9090'
    networks:
      - monitoring-network
  grafana:
    image:
      grafana/grafana-enterprise
    container_name:
      garafana
    hostname:
      grafana
    restart:
      unless-stopped
    volumes:
      - $GRAFANA_VOLUME:/var/lib/grafana
    ports:
      - '3000:3000'
    networks:
      - monitoring-network    
  loki:
    image: grafana/loki:2.8.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring-network
  promtail:
    image: grafana/promtail:2.8.4
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - promtail-docker-config.yaml:/etc/promtail/promtail-docker-config.yaml
    command: -config.file=/etc/promtail/promtail-docker-config.yaml
    networks:
      - monitoring-network

networks:
  monitoring-network:
    name: $NETWORK_NAME
    external: true
