version: '3'
services:
  prometheus:
    image:
      prom/prometheus
    container_name:
      prometheus
    hostname:
      prometheus
    restart:
      unless-stopped
    volumes:
      - $PROMETHEUS_VOLUME:/prometheus
    ports:
      - '9090:9090'
    networks:
      - monitoring-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
  grafana:
    image:
      grafana/grafana-enterprise
    container_name:
      grafana
    hostname:
      grafana
    restart:
      unless-stopped
    volumes:
      - $GRAFANA_VOLUME:/var/lib/grafana
    ports:
      - '3000:3000'
    networks:
      - monitoring-network    
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
  loki:
    image: grafana/loki:2.8.4
    container_name:
      loki
    ports:
      - "3100:3100"
    restart:
      unless-stopped
    volumes:
      - ./loki-docker-config.yaml:/etc/loki/loki-docker-config.yaml
    command: -config.file=/etc/loki/loki-docker-config.yaml
    networks:
      - monitoring-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
  promtail:
    image: grafana/promtail:2.8.4
    container_name:
      promtail
    restart:
      unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail-docker-config.yaml:/etc/promtail/promtail-docker-config.yaml
    command: -config.file=/etc/promtail/promtail-docker-config.yaml
    networks:
      - monitoring-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

networks:
  monitoring-network:
    name: $NETWORK_NAME
    external: true
