version: '3'
services:
  prometheus:
    image:
      prom/prometheus
    container_name:
      prometheus
    hostname:
      prometheus
    restart:
      unless-stopped
    volumes:
      - /data/prometheus:/prometheus
    ports:
      - '9090:9090'
